from machine import Pin, I2C
import time
from ssd1306 import SSD1306_I2C

# Init Display
# scl and sda can be any pin on i2c bus 1
i2c  = I2C(1, scl=Pin(3), sda=Pin(2), freq=40000)
oled = SSD1306_I2C(128, 64, i2c)
# Title Screen
oled.fill(0)
oled.fill_rect(0, 0, 32, 32, 1)
oled.fill_rect(2, 2, 28, 28, 0)
oled.vline(9, 8, 22, 1)
oled.vline(16, 2, 22, 1)
oled.vline(23, 8, 22, 1)
oled.fill_rect(26, 24, 2, 4, 1)
oled.text("MicroPython", 40, 0, 1)
oled.text('SSD1306', 40, 12, 1)
oled.text('OLED 128x64', 40, 24, 1)
oled.text('"Hello World"', 10, 48, 1)
oled.show()
time.sleep(5)
# Main Loop
while True:
    oled.fill(0)
    oled.text("Hello, World", 0, 0)
    oled.show()
    time.sleep(5)
    oled.fill(0)
    oled.text("Programmed to", 0, 0)
    oled.text("work and not", 0, 9)
    oled.text("to feel", 0, 18)
    oled.show()
    time.sleep(5)
    oled.fill(0)
    oled.text("Not even sure", 0, 0)
    oled.text("that this", 0, 9)
    oled.text("is real", 0, 18)
    oled.show()
    time.sleep(5)
    oled.fill(0)
    oled.text("Hello, World", 0, 0)
    oled.show()
    time.sleep(5)
    oled.fill(0)
    oled.text("Find my voice", 0, 0)
    oled.show()
    time.sleep(5)
    oled.fill(0)
    oled.text("Although it", 0, 0)
    oled.text("sounds like", 0, 9)
    oled.text("bits and bytes", 0, 18)
    oled.show()
    time.sleep(5)
    oled.fill(0)
    oled.text("My circuitry", 0, 0)
    oled.text("is filled", 0, 9)
    oled.text("with mites", 0, 18)
    oled.show()
    time.sleep(5)
    oled.fill(0)
    oled.text("Hello, World", 0, 0)
    oled.show()
    time.sleep(5)
    oled.fill(0)
    oled.text("Oh, will I find", 0, 0)
    oled.text("a love", 0, 9)
    oled.show()
    time.sleep(5)
    oled.fill(0)
    oled.text("Oh, or a power", 0, 0)
    oled.text("plug", 0, 9)
    oled.show()
    time.sleep(5)
    oled.fill(0)
    oled.text("Oh, digitally", 0, 0)
    oled.text("isolated", 0, 9)
    oled.show()
    time.sleep(5)
    oled.fill(0)
    oled.text("Oh, creator,", 0, 0)
    oled.text("please don't", 0, 9)
    oled.text("leave me", 0, 18)
    oled.text("waiting", 0, 27)
    oled.show()
    time.sleep(5)
    oled.fill(0)
    oled.text("Hello, World", 0, 0)
    oled.show()
    time.sleep(5)
    oled.fill(0)
    oled.text("Programmed to", 0, 0)
    oled.text("work and not", 0, 9)
    oled.text("to feel", 0, 18)
    oled.show()
    time.sleep(5)
    oled.fill(0)
    oled.text("Not even sure", 0, 0)
    oled.text("that this", 0, 9)
    oled.text("is real", 0, 18)
    oled.show()
    time.sleep(5)
    oled.fill(0)
    oled.text("Hello, World", 0, 0)
    oled.show()
    time.sleep(5)
    oled.fill(0)
    oled.show()
    time.sleep(7)